# Replica config
# dssmaster:
#   login: admin
#   password: ciphergoeshere
#   sync:
#     computers: 1(yes) 2(bi-directional)
#     configurationProfiles: 1
#     files: 1
#     masters: 1
#     packages: 1
#     scripts: 1
#     workflows: 1
#   url: "http://master.local:60080"

multicast:
  address: '224.77.2.77'
  firstPort: '7800'
  interface: 'en0'
  maximumDataRatePerStream: '8'
  minimumClientDataRate: '15'
  reconvertBeforeScanning: 'NO'
  simultaneousStreams: '4'
  ttl: '3'
notifications:
  TLS: false
  includeLogs: false
  level: 'none'
  login: ''
  password: ''
  recipients: []
  sender: ''
  smtp: ''
repository:
  hostPrimaryKey: 'dstudio-host-serial-number'
  mountOptions: ''
  password: 'password'
  subFolder: ''
  url: 'afp://hostname/ds_repo'
  user: 'deploystudiouser'
role: 'master'
security:
  adminGroup: ''
  assistantGroup: ''
  interface: 'any'
  port: '60080'
  rejectUnknownComputers: 'NO'
  sslKey: ''
version: 1.0 # No relation to DeployStudio Version