# This name is reported to the client and shown in some dialogs
name: 'Spirit Server'

# Local path to the repository, relative to rack start directory
repository_root: './ds_repo'

# Server version reported to the client, should match if you don't want
# warnings.
version: '1.6.12'

# Our version number, prefixed with the DS server version it emulates
spirit_version: '1.6.12.1'

# Admin credentials - Eventually this will tie into some actual authentication
# service
username: 'admin'
password: 'secret'

# Response format - Changed to binary sometime around 1.6.8
# If not true, reverts to xml encoded property lists.
respond_binary: True

# The OS X minor version to report that this system is running.
# Default 9 (10.9)
host_system_version: 9
