# This name is reported to the client and shown in some dialogs
name: 'Spirit Server'

# Local path to the repository, relative to rack start directory
repository_root: './ds_repo'

# Server version reported to the client, should match if you don't want
# warnings.
version: '1.6.12'

# Our version number, prefixed with the DS server version it emulates
spirit_version: '1.6.12.1'

# Admin credentials - Eventually this will tie into some actual authentication
# service
username: 'admin'
password: 'secret'
